"""Add loan table

Revision ID: a5bcff0a12c8
Revises: 35194c67d198
Create Date: 2026-09-23 10:48:26.877551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5bcff0a12c8'
down_revision = '35194c67d198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('business', sa.String(length=100), nullable=True),
    sa.Column('jobs_reatained', sa.Integer(), nullable=True),
    sa.Column('jobs_created', sa.Integer(), nullable=True),
    sa.Column('guaranteed_approved__loan', sa.Float(), nullable=True),
    sa.Column('low_documentation_loan', sa.String(length=20), nullable=True),
    sa.Column('demography', sa.String(length=50), nullable=True),
    sa.Column('state_of_bank', sa.String(length=50), nullable=True),
    sa.Column('chargedoff_amount', sa.Float(), nullable=True),
    sa.Column('borrower_city', sa.String(length=50), nullable=True),
    sa.Column('borrower_state', sa.String(length=50), nullable=True),
    sa.Column('gross_amount_balance', sa.Float(), nullable=True),
    sa.Column('count_employees', sa.Integer(), nullable=True),
    sa.Column('classification_code', sa.String(length=50), nullable=True),
    sa.Column('loan_approved_gross', sa.Float(), nullable=True),
    sa.Column('gross_amount_disbursed', sa.Float(), nullable=True),
    sa.Column('loan_term', sa.Integer(), nullable=True),
    sa.Column('code_franchise', sa.String(length=50), nullable=True),
    sa.Column('name_of_bank', sa.String(length=50), nullable=True),
    sa.Column('revolving_credit_line', sa.String(length=50), nullable=True),
    sa.Column('prediction', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['officer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan')
    # ### end Alembic commands ###
